name: Test

on:
  push:
    branches: [ 'master' ]
  pull_request:
    types: [ 'opened', 'synchronize', 'reopened' ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ '8.2', '8.3' ]

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer:v2

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: php-${{ matrix.php-version }}-composer-

      - name: Validate Composer Files
        run: composer validate

      - name: Install Dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Prepare App Installation
        run: |
          mkdir -p data
          composer db:initialize

      - name: Execute Static Code Analysis
        run: composer workflow:analyze

      - name: Execute Unit, Integration and Acceptance Tests
        run: composer workflow:test
